services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma-ui
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql                    # Points to the MySQL service
      PMA_USER: todo_user               # Non-root user
      PMA_PASSWORD: todo_pass           # Password for todo_user
      PMA_ARBITRARY: 1                  # Allows login with arbitrary users (optional)
    networks:
      - todo-network
    depends_on:
      - mysql

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data: {}